apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://10.0.2.15:16443
    certificate-authority: /root/.kube/ca.crt
users:
- name: johndoe
  user:
    client-certificate: /root/k8s-johndoe/johndoe.crt
    client-key: /root/k8s-johndoe/johndoe.key
contexts:
- name: johndoe-context
  context:
    cluster: my-cluster
    user: johndoe
current-context: johndoe-context
